server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/tiktok?useSSL=false&serverTimezone=UTC&character_set_server=utf8mb4&useUnicode=true
  data:
    redis:
      port: 6379
      host: 192.168.106.129
      password: ${REDIS_PASSWORD}
  elasticsearch:
    uris: 192.168.106.129:9200
  profiles:
    active: dev
  mail:
    sendgrid:
      api-key: ${SENDGRID_API_KEY}

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  rabbitmq:
    host: 192.168.106.129
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
    stream:
      virtual-host: /


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.example.tiktok.entity,org.example.tiktok.dto
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: ${JWT_SECRET}
  expire: 86400000  # 24小时（单位：毫秒）

pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

aliyun:
  oss:
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET}
