server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/tiktok?useSSL=false&serverTimezone=UTC&characterEncoding=utf8mb4&useUnicode=true
  data:
    redis:
      port: 6379
      host: 192.168.106.129
      password: ${REDIS_PASSWORD}
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.example.tiktok.entity
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: ${JWT_SECRET}
  expire: 86400000  # 24小时（单位：毫秒）

pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

aliyun:
  oss:
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET}
